<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Unserviceable Equipment Monitoring</title>
  <link rel="stylesheet" href="homepage.css">
</head>
<body>
<aside class="dashboard-sidebar">
  <nav>
    <ul class="sidebar-nav-list">
      <li>
        <a href="dashboard.php" class="sidebar-link">
          <span class="sidebar-icon">
            <img src="report.png" alt="Reports" width="22" height="22" style="vertical-align:middle;">
          </span>
          Dashboard
        </a>
      </li>
      <li></li>
      <li>
        <a href="eqmt_management.php" class="sidebar-link active">
          <span class="sidebar-icon">
            <img src="home.png" alt="Home" width="22" height="22" style="vertical-align:middle;">
          </span>
          Equipment Management
        </a>
      </li>
        <a href="user_management.php" class="sidebar-link">
          <span class="sidebar-icon">
            <img src="management.png" alt="User Management" width="22" height="22" style="vertical-align:middle;">
          </span>
          User Management
        </a>
      </li>
     <hr class="sidebar-divider">
      <div class="sidebar-user-profile">
  <div class="sidebar-user-avatar">
    <img src="user_photo.png">
  </div>
  <div class="sidebar-user-role">admin</div>
  <div class="sidebar-user-name">Rank Name + Unit</div>
</div>
      <li class="sidebar-signout">
        <button class="signout-btn" id="signoutBtn" type="button">
          <span class="sidebar-icon">
            <img src="signout.png" alt="Sign out" width="25" height="25" style="vertical-align:left;">
          </span>
          Sign out
        </button>
      </li>
    </ul>
  </nav>
</aside>
<div class="main-content-area">
  <header class="dashboard-header">
    <div class="logo-header">
      <img src="mc6logo.png" alt="Logo">
      <h1 class="dashboard-title">Manage Equipment</h1>
    </div>
  </header>
  <main class="dashboard-content">
    <section class="dashboard-table-box">
      <div class="dashboard-actions-table-wrap">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 18px;">
          <div>
            <h2 style="font-size: 1.25rem; font-weight: 700; margin: 0;">Equipment Inventory</h2>
            <p style="font-size: 1rem; color: var(--muted); margin: 2px 0 0 0;">List of all unserviceable equipment</p>
          </div>
          <div style="display: flex; align-items: center; gap: 18px;">
            <label for="categoryFilter" style="font-weight: 600; color: #222; margin-right: 6px;">Filter:</label>
            <select id="categoryFilter"></select>
            <input type="text" id="searchEquipment" placeholder="Search equipment..." style="padding: 12px 16px; border: 1px solid var(--border); border-radius: 8px; font-size: 1rem; margin-left: 12px;">
            <button class="modern-action-btn" id="addEquipmentBtn" style="margin-left: 12px; background: #e53935; color: #fff;">Add Equipment</button>
          </div>
        </div>
        <div class="dashboard-table-responsive">
          <table class="equipment-table">
            <thead>
              <tr>
                <th>Serial Number</th>
                <th>Particular</th>
                <th>Specification</th>
                <th>Category</th>
                <th>Unit In-charged</th>
                <th>Location</th>
                <th>Status</th>
                <th>Remarks</th>
                <th>Repair Level</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody id="equipment-table-body">
              <!-- Equipment rows generated by JS -->
            </tbody>
          </table>
        </div>
        <div id="equipment-count-label" style="margin: 16px 0 0 12px; font-size: 1.08em; font-weight: 700; color: #334155;"></div>
        <div id="pagination-controls-wrap"></div>
      </div>
    </section>
  </main>
  <!-- Modals can be static or dynamically loaded via JS -->
  <footer class="dashboard-footer">
    <span class="footer-muted">UEMS © Philippine Marine Corps 2025</span>
  </footer>
</div>
<!-- <script src="homepagejs.js"></script>
<script src="sidebar-active.js"></script> -->
</body>
</html>